export const ALL_VENTAS_REQUEST = "ALL_VENTAS_REQUEST";
export const ALL_VENTAS_SUCCESS = "ALL_VENTAS_SUCCESS";
export const ALL_VENTAS_FAIL = "ALL_VENTAS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";